lexik_jwt_authentication:
  secret_key: '%kernel.project_dir%/config/jwt/private.pem'
  public_key: '%kernel.project_dir%/config/jwt/public.pem'
  pass_phrase: ''  # Laisse vide sauf si tu as mis une passphrase
  token_ttl: 3600  # Durée de validité du token en secondes (1 heure)
