services:
  database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
      MYSQL_USER: ${MYSQL_USER:-app}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-3-!zPv%2X62Zo}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-3-!zPv%2X62Zo}
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - database_data:/var/lib/mysql:rw

volumes:
  database_data:
